kafka.host: localhost:9092
server.port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8091/user
    client:
      client-id: routingservice

spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1