version: '3'

services:
  configserver:
    image: local.config-server
    build: configserver
    ports:
      - "8888:8888"
  routing-service:
    image: local.routing-service
    build: routing-service
    ports:
      - "8082:8082"
  service-discovery:
    image: local.service-discovery
    build: service-discovery
    ports:
      - "8761:8761"