#zuul:
#  ignored-services: "*"
#  prefix: /v1/shipping
#  routes:
#    routing-service: /routing/**
#    cargo-service: /cargo/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka